/**
 * This file is generated by program. Do not modify this file!
 * Please modify ".Function.Extra.h" instead. All the modification in this file will be cleared!
 */

#ifndef Functions_H
#define Functions_H

#define default default_value

struct Draw_Group_x_y{
	double x;
	double y;
};
struct DrawCurvedB_Group_x_y{
	double x;
	double y;
};
struct DrawCurvedBT_Group_x_y{
	double x;
	double y;
};
struct DrawCurvedBT_Group_p_q{
	double p;
	double q;
};
struct DrawCurvedL_Group_x_y{
	double x;
	double y;
};
struct DrawCurvedLR_Group_x_y{
	double x;
	double y;
};
struct DrawCurvedLR_Group_p_q{
	double p;
	double q;
};
struct DrawCurvedR_Group_x_y{
	double x;
	double y;
};
struct DrawCurvedT_Group_x_y{
	double x;
	double y;
};
struct Judge_Group_min_max{
	double min;
	double max;
};
struct MoveParticleEffect_Group_x_y{
	double x;
	double y;
};
struct SpawnParticleEffect_Group_x_y{
	double x;
	double y;
};
struct Switch_Group_test_consequent{
	double test;
	double consequent;
};
struct SwitchWithDefault_Group_test_consequent{
	double test;
	double consequent;
};
double Abs(double value);
double Add(const vector<double> &value);
double AddLifeScheduled(double value, double time);
double And(const vector<double> &value);
double Arccos(double value);
double Arcsin(double value);
double Arctan(double value);
double Arctan2(double y, double x);
double BeatToBPM(double beat);
double BeatToStartingBeat(double beat);
double BeatToStartingTime(double beat);
double BeatToTime(double beat);
double Block(double body);
double Break(double count, double value);
double Ceil(double value);
double Clamp(double x, double a, double b);
double Copy(double srcId, double srcIndex, double dstId, double dstIndex, double count);
double Cos(double value);
double Cosh(double value);
double DebugLog(double value);
double DebugPause();
double DecrementPost(double id, double index);
double DecrementPostPointed(double id, double index, double offset);
double DecrementPostShifted(double id, double x, double y, double s);
double DecrementPre(double id, double index);
double DecrementPrePointed(double id, double index, double offset);
double DecrementPreShifted(double id, double x, double y, double s);
double Degree(double value);
double DestroyParticleEffect(double particleId);
double Divide(const vector<double> &value);
double DoWhile(double body, double test);
double Draw(double id, Draw_Group_x_y x_y0, Draw_Group_x_y x_y1, Draw_Group_x_y x_y2, Draw_Group_x_y x_y3, double z1, double a, double z2, double z3, double z4);
double DrawCurvedB(double id, DrawCurvedB_Group_x_y x_y0, DrawCurvedB_Group_x_y x_y1, DrawCurvedB_Group_x_y x_y2, DrawCurvedB_Group_x_y x_y3, double z1, double a, double n, double p, double q, double z2, double z3, double z4);
double DrawCurvedBT(double id, DrawCurvedBT_Group_x_y x_y0, DrawCurvedBT_Group_x_y x_y1, DrawCurvedBT_Group_x_y x_y2, DrawCurvedBT_Group_x_y x_y3, double z1, double a, double n, DrawCurvedBT_Group_p_q p_q0, DrawCurvedBT_Group_p_q p_q1, double z2, double z3, double z4);
double DrawCurvedL(double id, DrawCurvedL_Group_x_y x_y0, DrawCurvedL_Group_x_y x_y1, DrawCurvedL_Group_x_y x_y2, DrawCurvedL_Group_x_y x_y3, double z1, double a, double n, double p, double q, double z2, double z3, double z4);
double DrawCurvedLR(double id, DrawCurvedLR_Group_x_y x_y0, DrawCurvedLR_Group_x_y x_y1, DrawCurvedLR_Group_x_y x_y2, DrawCurvedLR_Group_x_y x_y3, double z1, double a, double n, DrawCurvedLR_Group_p_q p_q0, DrawCurvedLR_Group_p_q p_q1, double z2, double z3, double z4);
double DrawCurvedR(double id, DrawCurvedR_Group_x_y x_y0, DrawCurvedR_Group_x_y x_y1, DrawCurvedR_Group_x_y x_y2, DrawCurvedR_Group_x_y x_y3, double z1, double a, double n, double p, double q, double z2, double z3, double z4);
double DrawCurvedT(double id, DrawCurvedT_Group_x_y x_y0, DrawCurvedT_Group_x_y x_y1, DrawCurvedT_Group_x_y x_y2, DrawCurvedT_Group_x_y x_y3, double z1, double a, double n, double p, double q, double z2, double z3, double z4);
double EaseInBack(double value);
double EaseInCirc(double value);
double EaseInCubic(double value);
double EaseInElastic(double value);
double EaseInExpo(double value);
double EaseInOutBack(double value);
double EaseInOutCirc(double value);
double EaseInOutCubic(double value);
double EaseInOutElastic(double value);
double EaseInOutExpo(double value);
double EaseInOutQuad(double value);
double EaseInOutQuart(double value);
double EaseInOutQuint(double value);
double EaseInOutSine(double value);
double EaseInQuad(double value);
double EaseInQuart(double value);
double EaseInQuint(double value);
double EaseInSine(double value);
double EaseOutBack(double value);
double EaseOutCirc(double value);
double EaseOutCubic(double value);
double EaseOutElastic(double value);
double EaseOutExpo(double value);
double EaseOutInBack(double value);
double EaseOutInCirc(double value);
double EaseOutInCubic(double value);
double EaseOutInElastic(double value);
double EaseOutInExpo(double value);
double EaseOutInQuad(double value);
double EaseOutInQuart(double value);
double EaseOutInQuint(double value);
double EaseOutInSine(double value);
double EaseOutQuad(double value);
double EaseOutQuart(double value);
double EaseOutQuint(double value);
double EaseOutSine(double value);
double Equal(double lhs, double rhs);
double Execute(const vector<double> &value);
double Execute0(const vector<double> &value);
double ExportValue(double index, double value);
double Floor(double value);
double Frac(double value);
double Get(double id, double index);
double GetPointed(double id, double index, double offset);
double GetShifted(double id, double x, double y, double s);
double Greater(double lhs, double rhs);
double GreaterOr(double lhs, double rhs);
double HasEffectClip(double id);
double HasParticleEffect(double id);
double HasSkinSprite(double id);
double If(double test, double consequent, double alternate);
double IncrementPost(double id, double index);
double IncrementPostPointed(double id, double index, double offset);
double IncrementPostShifted(double id, double x, double y, double s);
double IncrementPre(double id, double index);
double IncrementPrePointed(double id, double index, double offset);
double IncrementPreShifted(double id, double x, double y, double s);
double Judge(double source, double target, Judge_Group_min_max perfect, Judge_Group_min_max great, Judge_Group_min_max good);
double JudgeSimple(double source, double target, double perfect, double great, double good);
double JumpLoop(const vector<double> &branch);
double Lerp(double x, double y, double s);
double LerpClamped(double x, double y, double s);
double Less(double lhs, double rhs);
double LessOr(double lhs, double rhs);
double Log(double value);
double Max(double x, double y);
double Min(double x, double y);
double Mod(const vector<double> &value);
double MoveParticleEffect(double particleId, MoveParticleEffect_Group_x_y x_y0, MoveParticleEffect_Group_x_y x_y1, MoveParticleEffect_Group_x_y x_y2, MoveParticleEffect_Group_x_y x_y3);
double Multiply(const vector<double> &value);
double Negate(double value);
double Not(double value);
double NotEqual(double lhs, double rhs);
double Or(const vector<double> &value);
double Paint(double id, double x, double y, double size, double rotation, double z, double a);
double Play(double id, double distance);
double PlayLooped(double id);
double PlayLoopedScheduled(double id, double startTime);
double PlayScheduled(double id, double time, double distance);
double Power(const vector<double> &value);
double Print(double value, double format, double decimalPlaces, double anchorX, double anchorY, double pivotX, double pivotY, double width, double height, double rotation, double color, double alpha, double horizontalAlign, double background);
double Radian(double value);
double Random(double min, double max);
double RandomInteger(double min, double max);
double Rem(const vector<double> &value);
double Remap(double a, double b, double c, double d, double x);
double RemapClamped(double a, double b, double c, double d, double x);
double Round(double value);
double Set(double id, double index, double value);
double SetAdd(double id, double index, double value);
double SetAddPointed(double id, double index, double offset, double value);
double SetAddShifted(double id, double x, double y, double s, double value);
double SetDivide(double id, double index, double value);
double SetDividePointed(double id, double index, double offset, double value);
double SetDivideShifted(double id, double x, double y, double s, double value);
double SetMod(double id, double index, double value);
double SetModPointed(double id, double index, double offset, double value);
double SetModShifted(double id, double x, double y, double s, double value);
double SetMultiply(double id, double index, double value);
double SetMultiplyPointed(double id, double index, double offset, double value);
double SetMultiplyShifted(double id, double x, double y, double s, double value);
double SetPointed(double id, double index, double offset, double value);
double SetPower(double id, double index, double value);
double SetPowerPointed(double id, double index, double offset, double value);
double SetPowerShifted(double id, double x, double y, double s, double value);
double SetRem(double id, double index, double value);
double SetRemPointed(double id, double index, double offset, double value);
double SetRemShifted(double id, double x, double y, double s, double value);
double SetShifted(double id, double x, double y, double s, double value);
double SetSubtract(double id, double index, double value);
double SetSubtractPointed(double id, double index, double offset, double value);
double SetSubtractShifted(double id, double x, double y, double s, double value);
double Sign(double value);
double Sin(double value);
double Sinh(double value);
double Spawn(double id, const vector<double> &memory);
double SpawnParticleEffect(double id, SpawnParticleEffect_Group_x_y x_y0, SpawnParticleEffect_Group_x_y x_y1, SpawnParticleEffect_Group_x_y x_y2, SpawnParticleEffect_Group_x_y x_y3, double duration, double isLooped);
double StackEnter(double size);
double StackGet(double offset);
double StackGetFrame(double offset);
double StackGetFramePointer();
double StackGetPointer();
double StackGrow(double size);
double StackInit();
double StackLeave();
double StackPop();
double StackPush(double value);
double StackSet(double offset, double value);
double StackSetFrame(double offset, double value);
double StackSetFramePointer(double value);
double StackSetPointer(double value);
double StopLooped(double loopId);
double StopLoopedScheduled(double loopId, double endTime);
double StreamGetNextKey(double id, double key);
double StreamGetPreviousKey(double id, double key);
double StreamGetValue(double id, double key);
double StreamHas(double id, double key);
double StreamSet(double id, double key, double value);
double Subtract(const vector<double> &value);
double Switch(double discriminant, const vector<Switch_Group_test_consequent> &test_consequent);
double SwitchInteger(double discriminant, const vector<double> &consequent);
double SwitchIntegerWithDefault(double discriminant, const vector<double> &consequent, double default);
double SwitchWithDefault(double discriminant, const vector<SwitchWithDefault_Group_test_consequent> &test_consequent, double default);
double Tan(double value);
double Tanh(double value);
double TimeToScaledTime(double time);
double TimeToStartingScaledTime(double time);
double TimeToStartingTime(double time);
double TimeToTimeScale(double time);
double Trunc(double value);
double Unlerp(double a, double b, double x);
double UnlerpClamped(double a, double b, double x);
double While(double test, double body);
double RunCode(int nodeId);
#include"Abs.h" // Modified
#include"Add.h" // Modified
#include"AddLifeScheduled.h"
#include"And.h" // Modified
#include"Arccos.h" // Modified
#include"Arcsin.h" // Modified
#include"Arctan.h" // Modified
#include"Arctan2.h" // Modified
#include"BeatToBPM.h" // Modified
#include"BeatToStartingBeat.h" // Modified
#include"BeatToStartingTime.h" // Modified
#include"BeatToTime.h" // Modified
#include"Block.h" // Modified
#include"Break.h" // Modified
#include"Ceil.h" // Modified
#include"Clamp.h" // Modified
#include"Copy.h" // Modified
#include"Cos.h" // Modified
#include"Cosh.h" // Modified
#include"DebugLog.h" // Modified
#include"DebugPause.h" // Modified
#include"DecrementPost.h" // Modified
#include"DecrementPostPointed.h" // Modified
#include"DecrementPostShifted.h" // Modified
#include"DecrementPre.h" // Modified
#include"DecrementPrePointed.h" // Modified
#include"DecrementPreShifted.h" // Modified
#include"Degree.h" // Modified
#include"DestroyParticleEffect.h" // Modified
#include"Divide.h" // Modified
#include"DoWhile.h" // Modified
#include"Draw.h" // Modified
#include"DrawCurvedB.h"
#include"DrawCurvedBT.h"
#include"DrawCurvedL.h"
#include"DrawCurvedLR.h"
#include"DrawCurvedR.h"
#include"DrawCurvedT.h"
#include"EaseInBack.h" // Modified
#include"EaseInCirc.h" // Modified
#include"EaseInCubic.h" // Modified
#include"EaseInElastic.h" // Modified
#include"EaseInExpo.h" // Modified
#include"EaseInOutBack.h" // Modified
#include"EaseInOutCirc.h" // Modified
#include"EaseInOutCubic.h" // Modified
#include"EaseInOutElastic.h" // Modified
#include"EaseInOutExpo.h" // Modified
#include"EaseInOutQuad.h" // Modified
#include"EaseInOutQuart.h" // Modified
#include"EaseInOutQuint.h" // Modified
#include"EaseInOutSine.h" // Modified
#include"EaseInQuad.h" // Modified
#include"EaseInQuart.h" // Modified
#include"EaseInQuint.h" // Modified
#include"EaseInSine.h" // Modified
#include"EaseOutBack.h" // Modified
#include"EaseOutCirc.h" // Modified
#include"EaseOutCubic.h" // Modified
#include"EaseOutElastic.h" // Modified
#include"EaseOutExpo.h" // Modified
#include"EaseOutInBack.h" // Modified
#include"EaseOutInCirc.h" // Modified
#include"EaseOutInCubic.h" // Modified
#include"EaseOutInElastic.h" // Modified
#include"EaseOutInExpo.h" // Modified
#include"EaseOutInQuad.h" // Modified
#include"EaseOutInQuart.h" // Modified
#include"EaseOutInQuint.h" // Modified
#include"EaseOutInSine.h" // Modified
#include"EaseOutQuad.h" // Modified
#include"EaseOutQuart.h" // Modified
#include"EaseOutQuint.h" // Modified
#include"EaseOutSine.h" // Modified
#include"Equal.h" // Modified
#include"Execute.h" // Modified
#include"Execute0.h" // Modified
#include"ExportValue.h"
#include"Floor.h" // Modified
#include"Frac.h" // Modified
#include"Get.h" // Modified
#include"GetPointed.h" // Modified
#include"GetShifted.h" // Modified
#include"Greater.h" // Modified
#include"GreaterOr.h" // Modified
#include"HasEffectClip.h" // Modified
#include"HasParticleEffect.h" // Modified
#include"HasSkinSprite.h" // Modified
#include"If.h" // Modified
#include"IncrementPost.h" // Modified
#include"IncrementPostPointed.h" // Modified
#include"IncrementPostShifted.h" // Modified
#include"IncrementPre.h" // Modified
#include"IncrementPrePointed.h" // Modified
#include"IncrementPreShifted.h" // Modified
#include"Judge.h" // Modified
#include"JudgeSimple.h" // Modified
#include"JumpLoop.h" // Modified
#include"Lerp.h" // Modified
#include"LerpClamped.h" // Modified
#include"Less.h" // Modified
#include"LessOr.h" // Modified
#include"Log.h" // Modified
#include"Max.h" // Modified
#include"Min.h" // Modified
#include"Mod.h" // Modified
#include"MoveParticleEffect.h" // Modified
#include"Multiply.h" // Modified
#include"Negate.h" // Modified
#include"Not.h" // Modified
#include"NotEqual.h" // Modified
#include"Or.h" // Modified
#include"Paint.h"
#include"Play.h"
#include"PlayLooped.h"
#include"PlayLoopedScheduled.h"
#include"PlayScheduled.h"
#include"Power.h" // Modified
#include"Print.h"
#include"Radian.h" // Modified
#include"Random.h" // Modified
#include"RandomInteger.h" // Modified
#include"Rem.h" // Modified
#include"Remap.h" // Modified
#include"RemapClamped.h" // Modified
#include"Round.h" // Modified
#include"Set.h" // Modified
#include"SetAdd.h" // Modified
#include"SetAddPointed.h" // Modified
#include"SetAddShifted.h" // Modified
#include"SetDivide.h" // Modified
#include"SetDividePointed.h" // Modified
#include"SetDivideShifted.h" // Modified
#include"SetMod.h" // Modified
#include"SetModPointed.h" // Modified
#include"SetModShifted.h" // Modified
#include"SetMultiply.h" // Modified
#include"SetMultiplyPointed.h" // Modified
#include"SetMultiplyShifted.h" // Modified
#include"SetPointed.h" // Modified
#include"SetPower.h" // Modified
#include"SetPowerPointed.h" // Modified
#include"SetPowerShifted.h" // Modified
#include"SetRem.h" // Modified
#include"SetRemPointed.h" // Modified
#include"SetRemShifted.h" // Modified
#include"SetShifted.h" // Modified
#include"SetSubtract.h" // Modified
#include"SetSubtractPointed.h" // Modified
#include"SetSubtractShifted.h" // Modified
#include"Sign.h" // Modified
#include"Sin.h" // Modified
#include"Sinh.h" // Modified
#include"Spawn.h" // Modified
#include"SpawnParticleEffect.h" // Modified
#include"StackEnter.h"
#include"StackGet.h"
#include"StackGetFrame.h"
#include"StackGetFramePointer.h"
#include"StackGetPointer.h"
#include"StackGrow.h"
#include"StackInit.h"
#include"StackLeave.h"
#include"StackPop.h"
#include"StackPush.h"
#include"StackSet.h"
#include"StackSetFrame.h"
#include"StackSetFramePointer.h"
#include"StackSetPointer.h"
#include"StopLooped.h"
#include"StopLoopedScheduled.h"
#include"StreamGetNextKey.h" // Modified
#include"StreamGetPreviousKey.h" // Modified
#include"StreamGetValue.h" // Modified
#include"StreamHas.h" // Modified
#include"StreamSet.h" // Modified
#include"Subtract.h" // Modified
#include"Switch.h" // Modified
#include"SwitchInteger.h" // Modified
#include"SwitchIntegerWithDefault.h" // Modified
#include"SwitchWithDefault.h" // Modified
#include"Tan.h" // Modified
#include"Tanh.h" // Modified
#include"TimeToScaledTime.h" // Modified
#include"TimeToStartingScaledTime.h" // Modified
#include"TimeToStartingTime.h" // Modified
#include"TimeToTimeScale.h" // Modified
#include"Trunc.h" // Modified
#include"Unlerp.h" // Modified
#include"UnlerpClamped.h" // Modified
#include"While.h" // Modified

#undef default

double RunCode(int nodeId) {
	beforeRunCode(nodeId);
	DataNode &node = nodes[nodeId];
	if (node.isValue) return node.value;
	int hash = node.hash;
	for (int i = 0; i < node.param.size(); i++) node.values[i] = node.param[i];
	if (hash == 354231728) { beforeRunMainCode(nodeId); double res = And(node.values); afterRunCode(nodeId); return res; }
	if (hash == 565864982) { beforeRunMainCode(nodeId); node.values.resize(1, 0); double res = Block(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 76217789) { beforeRunMainCode(nodeId); node.values.resize(2, 0); double res = Break(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 960814006) { beforeRunMainCode(nodeId); node.values.resize(2, 0); double res = DoWhile(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 4039265) { beforeRunMainCode(nodeId); node.values.resize(3, 0); double res = If(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 525528671) { beforeRunMainCode(nodeId); double res = JumpLoop(node.values); afterRunCode(nodeId); return res; }
	if (hash == 4371263) { beforeRunMainCode(nodeId); double res = Or(node.values); afterRunCode(nodeId); return res; }
	if (hash == 699327620) { beforeRunMainCode(nodeId); double res = Switch(node.values[0], [](vector<double> v){ vector<Switch_Group_test_consequent> res; for (int i = 0; i < v.size(); i += 2) res.push_back({ v[i], v[i + 1] }); return res; }(vector<double>(node.values.begin() + 1, node.values.end()))); afterRunCode(nodeId); return res; }
	if (hash == 303691296) { beforeRunMainCode(nodeId); double res = SwitchInteger(node.values[0], vector<double>(node.values.begin() + 1, node.values.end())); afterRunCode(nodeId); return res; }
	if (hash == 271289553) { beforeRunMainCode(nodeId); double res = SwitchIntegerWithDefault(node.values[0], vector<double>(node.values.begin() + 1, node.values.end() - 1), node.values.back()); afterRunCode(nodeId); return res; }
	if (hash == 188807862) { beforeRunMainCode(nodeId); double res = SwitchWithDefault(node.values[0], [](vector<double> v){ vector<SwitchWithDefault_Group_test_consequent> res; for (int i = 0; i < v.size(); i += 2) res.push_back({ v[i], v[i + 1] }); return res; }(vector<double>(node.values.begin() + 1, node.values.end() - 1)), node.values.back()); afterRunCode(nodeId); return res; }
	if (hash == 777427314) { beforeRunMainCode(nodeId); node.values.resize(2, 0); double res = While(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	node.currValueCount = 0;
	for (int i = 0; i < node.param.size(); i++) {
		node.values[i] = RunCode(node.param[i]);
		node.currValueCount++;
		if (breakCount) return afterRunCode(nodeId), 0;
	}
	beforeRunMainCode(nodeId);
	if (hash == 353567771) { node.values.resize(1, 0); double res = Abs(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 353678418) { double res = Add(node.values); afterRunCode(nodeId); return res; }
	if (hash == 130046266) { node.values.resize(2, 0); double res = AddLifeScheduled(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 296531894) { node.values.resize(1, 0); double res = Arccos(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 366539582) { node.values.resize(1, 0); double res = Arcsin(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 432883436) { node.values.resize(1, 0); double res = Arctan(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 996635837) { node.values.resize(2, 0); double res = Arctan2(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 920291988) { node.values.resize(1, 0); double res = BeatToBPM(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 151439847) { node.values.resize(1, 0); double res = BeatToStartingBeat(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 954235279) { node.values.resize(1, 0); double res = BeatToStartingTime(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 441471502) { node.values.resize(1, 0); double res = BeatToTime(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 590252476) { node.values.resize(1, 0); double res = Ceil(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 204936080) { node.values.resize(3, 0); double res = Clamp(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 260260473) { node.values.resize(5, 0); double res = Copy(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4]); afterRunCode(nodeId); return res; }
	if (hash == 487860078) { node.values.resize(1, 0); double res = Cos(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 260426449) { node.values.resize(1, 0); double res = Cosh(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 698631241) { node.values.resize(1, 0); double res = DebugLog(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 974003130) { node.values.resize(0, 0); double res = DebugPause(); afterRunCode(nodeId); return res; }
	if (hash == 126309183) { node.values.resize(2, 0); double res = DecrementPost(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 597367328) { node.values.resize(3, 0); double res = DecrementPostPointed(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 436750493) { node.values.resize(4, 0); double res = DecrementPostShifted(node.values[0], node.values[1], node.values[2], node.values[3]); afterRunCode(nodeId); return res; }
	if (hash == 951829923) { node.values.resize(2, 0); double res = DecrementPre(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 411951963) { node.values.resize(3, 0); double res = DecrementPrePointed(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 251335128) { node.values.resize(4, 0); double res = DecrementPreShifted(node.values[0], node.values[1], node.values[2], node.values[3]); afterRunCode(nodeId); return res; }
	if (hash == 485224518) { node.values.resize(1, 0); double res = Degree(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 281239407) { node.values.resize(1, 0); double res = DestroyParticleEffect(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 128416253) { double res = Divide(node.values); afterRunCode(nodeId); return res; }
	if (hash == 323137368) { node.values.resize(14, 0); double res = Draw(node.values[0], { node.values[1], node.values[2] }, { node.values[3], node.values[4] }, { node.values[5], node.values[6] }, { node.values[7], node.values[8] }, node.values[9], node.values[10], node.values[11], node.values[12], node.values[13]); afterRunCode(nodeId); return res; }
	if (hash == 59532960) { node.values.resize(17, 0); double res = DrawCurvedB(node.values[0], { node.values[1], node.values[2] }, { node.values[3], node.values[4] }, { node.values[5], node.values[6] }, { node.values[7], node.values[8] }, node.values[9], node.values[10], node.values[11], node.values[12], node.values[13], node.values[14], node.values[15], node.values[16]); afterRunCode(nodeId); return res; }
	if (hash == 810089297) { node.values.resize(19, 0); double res = DrawCurvedBT(node.values[0], { node.values[1], node.values[2] }, { node.values[3], node.values[4] }, { node.values[5], node.values[6] }, { node.values[7], node.values[8] }, node.values[9], node.values[10], node.values[11], { node.values[12], node.values[13] }, { node.values[14], node.values[15] }, node.values[16], node.values[17], node.values[18]); afterRunCode(nodeId); return res; }
	if (hash == 59532970) { node.values.resize(17, 0); double res = DrawCurvedL(node.values[0], { node.values[1], node.values[2] }, { node.values[3], node.values[4] }, { node.values[5], node.values[6] }, { node.values[7], node.values[8] }, node.values[9], node.values[10], node.values[11], node.values[12], node.values[13], node.values[14], node.values[15], node.values[16]); afterRunCode(nodeId); return res; }
	if (hash == 810642605) { node.values.resize(19, 0); double res = DrawCurvedLR(node.values[0], { node.values[1], node.values[2] }, { node.values[3], node.values[4] }, { node.values[5], node.values[6] }, { node.values[7], node.values[8] }, node.values[9], node.values[10], node.values[11], { node.values[12], node.values[13] }, { node.values[14], node.values[15] }, node.values[16], node.values[17], node.values[18]); afterRunCode(nodeId); return res; }
	if (hash == 59532976) { node.values.resize(17, 0); double res = DrawCurvedR(node.values[0], { node.values[1], node.values[2] }, { node.values[3], node.values[4] }, { node.values[5], node.values[6] }, { node.values[7], node.values[8] }, node.values[9], node.values[10], node.values[11], node.values[12], node.values[13], node.values[14], node.values[15], node.values[16]); afterRunCode(nodeId); return res; }
	if (hash == 59532978) { node.values.resize(17, 0); double res = DrawCurvedT(node.values[0], { node.values[1], node.values[2] }, { node.values[3], node.values[4] }, { node.values[5], node.values[6] }, { node.values[7], node.values[8] }, node.values[9], node.values[10], node.values[11], node.values[12], node.values[13], node.values[14], node.values[15], node.values[16]); afterRunCode(nodeId); return res; }
	if (hash == 11061850) { node.values.resize(1, 0); double res = EaseInBack(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 409531179) { node.values.resize(1, 0); double res = EaseInCirc(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 907745886) { node.values.resize(1, 0); double res = EaseInCubic(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 872316926) { node.values.resize(1, 0); double res = EaseInElastic(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 139668418) { node.values.resize(1, 0); double res = EaseInExpo(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 111542351) { node.values.resize(1, 0); double res = EaseInOutBack(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 510011680) { node.values.resize(1, 0); double res = EaseInOutCirc(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 373300507) { node.values.resize(1, 0); double res = EaseInOutCubic(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 684063757) { node.values.resize(1, 0); double res = EaseInOutElastic(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 240148919) { node.values.resize(1, 0); double res = EaseInOutExpo(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 395616415) { node.values.resize(1, 0); double res = EaseInOutQuad(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 350460531) { node.values.resize(1, 0); double res = EaseInOutQuart(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 884531223) { node.values.resize(1, 0); double res = EaseInOutQuint(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 319836760) { node.values.resize(1, 0); double res = EaseInOutSine(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 295135914) { node.values.resize(1, 0); double res = EaseInQuad(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 884905910) { node.values.resize(1, 0); double res = EaseInQuart(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 420732249) { node.values.resize(1, 0); double res = EaseInQuint(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 219356259) { node.values.resize(1, 0); double res = EaseInSine(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 880401475) { node.values.resize(1, 0); double res = EaseOutBack(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 280626451) { node.values.resize(1, 0); double res = EaseOutCirc(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 936143103) { node.values.resize(1, 0); double res = EaseOutCubic(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 193193749) { node.values.resize(1, 0); double res = EaseOutElastic(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 10763690) { node.values.resize(1, 0); double res = EaseOutExpo(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 61136430) { node.values.resize(1, 0); double res = EaseOutInBack(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 459605759) { node.values.resize(1, 0); double res = EaseOutInCirc(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 458007938) { node.values.resize(1, 0); double res = EaseOutInCubic(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 407244280) { node.values.resize(1, 0); double res = EaseOutInElastic(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 189742998) { node.values.resize(1, 0); double res = EaseOutInExpo(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 345210494) { node.values.resize(1, 0); double res = EaseOutInQuad(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 435167962) { node.values.resize(1, 0); double res = EaseOutInQuart(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 969238654) { node.values.resize(1, 0); double res = EaseOutInQuint(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 269430839) { node.values.resize(1, 0); double res = EaseOutInSine(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 166231186) { node.values.resize(1, 0); double res = EaseOutQuad(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 913303127) { node.values.resize(1, 0); double res = EaseOutQuart(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 449129466) { node.values.resize(1, 0); double res = EaseOutQuint(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 90451531) { node.values.resize(1, 0); double res = EaseOutSine(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 7307840) { node.values.resize(2, 0); double res = Equal(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 728009492) { double res = Execute(node.values); afterRunCode(nodeId); return res; }
	if (hash == 337069644) { double res = Execute0(node.values); afterRunCode(nodeId); return res; }
	if (hash == 864710536) { node.values.resize(2, 0); double res = ExportValue(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 864155499) { node.values.resize(1, 0); double res = Floor(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 49832060) { node.values.resize(1, 0); double res = Frac(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 754452777) { node.values.resize(2, 0); double res = Get(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 739376506) { node.values.resize(3, 0); double res = GetPointed(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 578759671) { node.values.resize(4, 0); double res = GetShifted(node.values[0], node.values[1], node.values[2], node.values[3]); afterRunCode(nodeId); return res; }
	if (hash == 784341691) { node.values.resize(2, 0); double res = Greater(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 489047347) { node.values.resize(2, 0); double res = GreaterOr(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 745520808) { node.values.resize(1, 0); double res = HasEffectClip(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 617304763) { node.values.resize(1, 0); double res = HasParticleEffect(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 426561527) { node.values.resize(1, 0); double res = HasSkinSprite(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 467576240) { node.values.resize(2, 0); double res = IncrementPost(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 393422730) { node.values.resize(3, 0); double res = IncrementPostPointed(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 232805895) { node.values.resize(4, 0); double res = IncrementPostShifted(node.values[0], node.values[1], node.values[2], node.values[3]); afterRunCode(nodeId); return res; }
	if (hash == 105571829) { node.values.resize(2, 0); double res = IncrementPre(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 227282) { node.values.resize(3, 0); double res = IncrementPrePointed(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 837854800) { node.values.resize(4, 0); double res = IncrementPreShifted(node.values[0], node.values[1], node.values[2], node.values[3]); afterRunCode(nodeId); return res; }
	if (hash == 195058411) { node.values.resize(8, 0); double res = Judge(node.values[0], node.values[1], { node.values[2], node.values[3] }, { node.values[4], node.values[5] }, { node.values[6], node.values[7] }); afterRunCode(nodeId); return res; }
	if (hash == 306765149) { node.values.resize(5, 0); double res = JudgeSimple(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4]); afterRunCode(nodeId); return res; }
	if (hash == 359121016) { node.values.resize(3, 0); double res = Lerp(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 810698092) { node.values.resize(3, 0); double res = LerpClamped(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 359176350) { node.values.resize(2, 0); double res = Less(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 781216003) { node.values.resize(2, 0); double res = LessOr(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 90694231) { node.values.resize(1, 0); double res = Log(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 156706116) { node.values.resize(2, 0); double res = Max(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 157148754) { node.values.resize(2, 0); double res = Min(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 157480730) { double res = Mod(node.values); afterRunCode(nodeId); return res; }
	if (hash == 397077946) { node.values.resize(9, 0); double res = MoveParticleEffect(node.values[0], { node.values[1], node.values[2] }, { node.values[3], node.values[4] }, { node.values[5], node.values[6] }, { node.values[7], node.values[8] }); afterRunCode(nodeId); return res; }
	if (hash == 456999699) { double res = Multiply(node.values); afterRunCode(nodeId); return res; }
	if (hash == 690257071) { node.values.resize(1, 0); double res = Negate(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 224267248) { node.values.resize(1, 0); double res = Not(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 888857026) { node.values.resize(2, 0); double res = NotEqual(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 714137881) { node.values.resize(7, 0); double res = Paint(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4], node.values[5], node.values[6]); afterRunCode(nodeId); return res; }
	if (hash == 279075336) { node.values.resize(2, 0); double res = Play(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 864609494) { node.values.resize(1, 0); double res = PlayLooped(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 535522527) { node.values.resize(2, 0); double res = PlayLoopedScheduled(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 638767463) { node.values.resize(3, 0); double res = PlayScheduled(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 733758265) { double res = Power(node.values); afterRunCode(nodeId); return res; }
	if (hash == 387531639) { node.values.resize(14, 0); double res = Print(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4], node.values[5], node.values[6], node.values[7], node.values[8], node.values[9], node.values[10], node.values[11], node.values[12], node.values[13]); afterRunCode(nodeId); return res; }
	if (hash == 274467485) { node.values.resize(1, 0); double res = Radian(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 571271874) { node.values.resize(2, 0); double res = Random(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 329539034) { node.values.resize(2, 0); double res = RandomInteger(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 490859939) { double res = Rem(node.values); afterRunCode(nodeId); return res; }
	if (hash == 582767275) { node.values.resize(5, 0); double res = Remap(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4]); afterRunCode(nodeId); return res; }
	if (hash == 519163494) { node.values.resize(5, 0); double res = RemapClamped(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4]); afterRunCode(nodeId); return res; }
	if (hash == 749496495) { node.values.resize(1, 0); double res = Round(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 557646448) { node.values.resize(3, 0); double res = Set(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 440238958) { node.values.resize(3, 0); double res = SetAdd(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 549239301) { node.values.resize(4, 0); double res = SetAddPointed(node.values[0], node.values[1], node.values[2], node.values[3]); afterRunCode(nodeId); return res; }
	if (hash == 388622466) { node.values.resize(5, 0); double res = SetAddShifted(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4]); afterRunCode(nodeId); return res; }
	if (hash == 877796936) { node.values.resize(3, 0); double res = SetDivide(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 709544358) { node.values.resize(4, 0); double res = SetDividePointed(node.values[0], node.values[1], node.values[2], node.values[3]); afterRunCode(nodeId); return res; }
	if (hash == 548927523) { node.values.resize(5, 0); double res = SetDivideShifted(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4]); afterRunCode(nodeId); return res; }
	if (hash == 244041270) { node.values.resize(3, 0); double res = SetMod(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 178739347) { node.values.resize(4, 0); double res = SetModPointed(node.values[0], node.values[1], node.values[2], node.values[3]); afterRunCode(nodeId); return res; }
	if (hash == 18122512) { node.values.resize(5, 0); double res = SetModShifted(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4]); afterRunCode(nodeId); return res; }
	if (hash == 1715004) { node.values.resize(3, 0); double res = SetMultiply(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 759087472) { node.values.resize(4, 0); double res = SetMultiplyPointed(node.values[0], node.values[1], node.values[2], node.values[3]); afterRunCode(nodeId); return res; }
	if (hash == 598470637) { node.values.resize(5, 0); double res = SetMultiplyShifted(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4]); afterRunCode(nodeId); return res; }
	if (hash == 657166202) { node.values.resize(4, 0); double res = SetPointed(node.values[0], node.values[1], node.values[2], node.values[3]); afterRunCode(nodeId); return res; }
	if (hash == 789988566) { node.values.resize(3, 0); double res = SetPower(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 160660600) { node.values.resize(4, 0); double res = SetPowerPointed(node.values[0], node.values[1], node.values[2], node.values[3]); afterRunCode(nodeId); return res; }
	if (hash == 43765) { node.values.resize(5, 0); double res = SetPowerShifted(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4]); afterRunCode(nodeId); return res; }
	if (hash == 577420479) { node.values.resize(3, 0); double res = SetRem(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 884049916) { node.values.resize(4, 0); double res = SetRemPointed(node.values[0], node.values[1], node.values[2], node.values[3]); afterRunCode(nodeId); return res; }
	if (hash == 723433081) { node.values.resize(5, 0); double res = SetRemShifted(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4]); afterRunCode(nodeId); return res; }
	if (hash == 496549367) { node.values.resize(5, 0); double res = SetShifted(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4]); afterRunCode(nodeId); return res; }
	if (hash == 963104304) { node.values.resize(3, 0); double res = SetSubtract(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 766475826) { node.values.resize(4, 0); double res = SetSubtractPointed(node.values[0], node.values[1], node.values[2], node.values[3]); afterRunCode(nodeId); return res; }
	if (hash == 605858991) { node.values.resize(5, 0); double res = SetSubtractShifted(node.values[0], node.values[1], node.values[2], node.values[3], node.values[4]); afterRunCode(nodeId); return res; }
	if (hash == 667334226) { node.values.resize(1, 0); double res = Sign(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 557867766) { node.values.resize(1, 0); double res = Sin(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 667721537) { node.values.resize(1, 0); double res = Sinh(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 849384964) { double res = Spawn(node.values[0], vector<double>(node.values.begin() + 1, node.values.end())); afterRunCode(nodeId); return res; }
	if (hash == 879387481) { node.values.resize(11, 0); double res = SpawnParticleEffect(node.values[0], { node.values[1], node.values[2] }, { node.values[3], node.values[4] }, { node.values[5], node.values[6] }, { node.values[7], node.values[8] }, node.values[9], node.values[10]); afterRunCode(nodeId); return res; }
	if (hash == 856994911) { node.values.resize(1, 0); double res = StackEnter(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 509746364) { node.values.resize(1, 0); double res = StackGet(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 218420376) { node.values.resize(1, 0); double res = StackGetFrame(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 158410069) { node.values.resize(0, 0); double res = StackGetFramePointer(); afterRunCode(nodeId); return res; }
	if (hash == 22715255) { node.values.resize(0, 0); double res = StackGetPointer(); afterRunCode(nodeId); return res; }
	if (hash == 249820459) { node.values.resize(1, 0); double res = StackGrow(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 707281527) { node.values.resize(0, 0); double res = StackInit(); afterRunCode(nodeId); return res; }
	if (hash == 840590048) { node.values.resize(0, 0); double res = StackLeave(); afterRunCode(nodeId); return res; }
	if (hash == 113133835) { node.values.resize(0, 0); double res = StackPop(); afterRunCode(nodeId); return res; }
	if (hash == 218771831) { node.values.resize(1, 0); double res = StackPush(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 312940035) { node.values.resize(2, 0); double res = StackSet(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 300484663) { node.values.resize(2, 0); double res = StackSetFrame(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 32197539) { node.values.resize(1, 0); double res = StackSetFramePointer(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 938749304) { node.values.resize(1, 0); double res = StackSetPointer(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 247726885) { node.values.resize(1, 0); double res = StopLooped(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 492142380) { node.values.resize(2, 0); double res = StopLoopedScheduled(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 114477946) { node.values.resize(2, 0); double res = StreamGetNextKey(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 396079855) { node.values.resize(2, 0); double res = StreamGetPreviousKey(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 480315785) { node.values.resize(2, 0); double res = StreamGetValue(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 631558434) { node.values.resize(2, 0); double res = StreamHas(node.values[0], node.values[1]); afterRunCode(nodeId); return res; }
	if (hash == 368186928) { node.values.resize(3, 0); double res = StreamSet(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 420144646) { double res = Subtract(node.values); afterRunCode(nodeId); return res; }
	if (hash == 624211620) { node.values.resize(1, 0); double res = Tan(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 995021230) { node.values.resize(1, 0); double res = Tanh(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 647454417) { node.values.resize(1, 0); double res = TimeToScaledTime(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 325884805) { node.values.resize(1, 0); double res = TimeToStartingScaledTime(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 409692508) { node.values.resize(1, 0); double res = TimeToStartingTime(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 973385866) { node.values.resize(1, 0); double res = TimeToTimeScale(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 488351831) { node.values.resize(1, 0); double res = Trunc(node.values[0]); afterRunCode(nodeId); return res; }
	if (hash == 583672445) { node.values.resize(3, 0); double res = Unlerp(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	if (hash == 417111798) { node.values.resize(3, 0); double res = UnlerpClamped(node.values[0], node.values[1], node.values[2]); afterRunCode(nodeId); return res; }
	assert(false);
	return 0;
}

#endif
